### ISSUE TITLE
Question about 01-introduction

### ISSUE THREAD

**Issue by joewiz** [CliffordAnderson/XQuery4Humanists#4]
Hey Cliff,

I was just giving the material a look over, and had one question: I wasn't quite clear what you're expecting the examples around lines 270-290 to return?  Here they are:

```xquery
let $ids :=
  <identifiers>
    <isbn num="13">978-0133507645</isbn>
    <isbn num="10">0133507645</isbn>
    <isbn num="13">978-0133507645</isbn>
  </identifiers>
where $ids/isbn/@num FIX ME! "13"
return $ids
```

```xquery
let $ids :=
  <identifiers>
    <isbn num="13">978-0133507645</isbn>
    <isbn num="10">0133507645</isbn>
    <isbn num="13">978-0133507645</isbn>
  </identifiers>
where some $id in ($ids/isbn/@num) satisfies FIX ME!
return $ids
```

My guess is that a student would expect that their change would result in a filtered list - only the `<isbn num="13">` entries. But nothing the student changes the `where` expression to would filter out the `<isbn num="10">` entries from the results. No matter what, editing only the where clause will only result in the entire  `<identifiers>` element or an empty sequence being returned.

As a result, I wasn't sure what you were trying to illustrate?  Sorry if I was misreading anything.

Joe

**Comment by CliffordAnderson** [comment]
Hi @joewiz !

Thanks for the careful reading of these sessions. I had in mind illustrating the difference between the `eq` and `=` operators.

```xquery
let $ids :=
  <identifiers>
    <isbn num="13">978-0133507645</isbn>
    <isbn num="10">0133507645</isbn>
    <isbn num="13">978-0133507645</isbn>
  </identifiers>
where $ids/isbn/@num = "13" (: not `eq` because we need implicit existential quantification :)
return $ids
```

```xquery
let $ids :=
  <identifiers>
    <isbn num="13">978-0133507645</isbn>
    <isbn num="10">0133507645</isbn>
    <isbn num="13">978-0133507645</isbn>
  </identifiers>
where some $id in ($ids/isbn/@num) satisfies xs:int($id) eq 13 (: or `=` :)
return $ids
```

Maybe not the clearest way to illustrate things? 

Best wishes,

Cliff

**Comment by joewiz** [comment]
Hi Cliff,

That is a good illustration.  I'd suggest just adding a sentence stating what the student should expect: 

> With your alterations, the first query should return the `<identifiers>` element if any of the `num` attributes equals 13. If you get no results or an error, then keep trying. (Hint: Should you replace `FIX ME!` with `eq` or `=`?

Similarly for the second one:

> With your alterations, the second query should return the `<identifiers>` element. (Hint: Should you replace `FIX ME!` with `$id eq 13` or `$id = 13`?

If conditional had been introduced at this point, we could've used that in the return clause. E.g.,

```xquery
xquery version "3.1";

let $ids :=
  <identifiers>
    <isbn num="13">978-0133507645</isbn>
    <isbn num="10">0133507645</isbn>
    <isbn num="13">978-0133507645</isbn>
  </identifiers>
return
  if (some $id in ($ids/isbn/@num) satisfies FIX ME!) then
    "One of the isbn elements is ISBN-13!"
  else 
    "Apparently, none of the isbn elements is ISBN-13. Keep trying!"
```

But I think the example is fine as is! It probably just needs a little explanation to make it understandable to someone working through it without an instructor in front of them.

**Comment by CliffordAnderson** [comment]
Thanks! Good suggestions for clarification.
