### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by amandafrench** [CliffordAnderson/XQuery4Humanists#6]
In introduction.md, there's a typo: 

```There is also an expression called typeswitch that let's you branch on types rather than values.```

"let's" should be "lets" 

=) Thanks for the lesson!

**Comment by CliffordAnderson** [comment]
Thank you! Great to have you in our workshop, @amandafrench!

**Comment by amandafrench** [comment]
Thanks! I enjoyed it!
