### ISSUE TITLE
map(*) cannot be serialized

### ISSUE THREAD

**Issue by lakonis** [CliffordAnderson/XQuery4Humanists#7]
Working on [chapter 05](https://github.com/CliffordAnderson/XQuery4Humanists/blob/master/05-Generating-JSON-and-CSV.md), in the first serialization attempt using `fn:serialize()`, 

> Once we've succeeded in generating an XQuery map/array representation of our data, then all we need to generate the JSON representation of this data is to serialize , or write out, the results as JSON. To do this we could use the fn:serialize()

basex (8.6.5) gives me the error : `[SENR0001] Items of type map(*) cannot be serialized`
Does it really work for you (after correction on line 13, missing `:=`) ?

**Comment by lakonis** [comment]
fixed with commit [3599a0e](https://github.com/CliffordAnderson/XQuery4Humanists/commit/3599a0ea467bc8411a75bfd8ba84723c863deb03)

**Comment by joewiz** [comment]
@lakonis Yes, very sorry for the typo there. We realized this during the session on Monday afternoon, and I just today got around to making the round of corrections to the text. Please take a look at the other changes, which include this and a couple of substantive corrections: https://github.com/CliffordAnderson/XQuery4Humanists/commit/3599a0ea467bc8411a75bfd8ba84723c863deb03. Thank you for the feedback!
